install:
  - set QTDIR=C:\Qt\5.9.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake OpenGestureControl/OpenGestureControlCore.pro
  - mingw32-make

notifications:
  - provider: Slack
    incoming_webhook:
      secure: fPwOVlKwrA1/lM4+77G3P/Ptagrbja0At1OGElHm/k1entDjSZSpPCBIOQPJDxCT0ixihy6+JkyAeIt6MD1Wt5nS2IdJghge484KzTnEDTE=
