install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - cd OpenGestureControl
  - qmake OpenGestureControl.pro
  - mingw32-make
  - cd ..
  - cd tests
  - qmake tests.pro
  - mingw32-make
  - cd release
  - C:\Qt\5.9\mingw53_32\bin\windeployqt --qmldir ..\..\OpenGestureControl tests.exe
  - copy ..\..\OpenGestureControl\libs\*.dll .
  - cd ..
  - xcopy ..\OpenGestureControl\modules modules /S /I
  - release\tests.exe
  - move release\*.gcno .
  - move release\*.gcda .
  - ps: |
      $env:PATH = 'C:\MinGW\bin;' + 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -g "*tests/*test*" -g "*tests/main.*"

notifications:
  - provider: Slack
    incoming_webhook:
      secure: fPwOVlKwrA1/lM4+77G3P/Ptagrbja0At1OGElHm/k1entDjSZSpPCBIOQPJDxCT0ixihy6+JkyAeIt6MD1Wt5nS2IdJghge484KzTnEDTE=
