######################################################################
# Automatically generated by qmake (3.0) Thu Nov 9 13:59:24 2017
######################################################################

QT += qml quick widgets testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
SOURCES += testbluetoothdevicelistmodel.cpp
